#!/bin/bash

sudo ufw --force reset

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw enable

sudo ufw allow proto tcp from 10.243.109.248 to any port 5672
sudo ufw allow proto tcp from 10.243.109.248 to any port 15672

sudo ufw deny in on any

sudo ufw logging on

sudo ufw status verbose


