<<<<<<< HEAD
[notaweatherapp]
BROKER_HOST = 10.243.120.72
BROKER_PORT = 5672
USER = notaweatherapp
PASSWORD = 1234
VHOST = IT490_vhost
EXCHANGE = IT490_exchange
QUEUE = Login
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
=======
[testServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
>>>>>>> 26247c39a6a644b4f70738d5e592b41719062489
